baseurl = "https://example.com/"
languageCode = "en-us"
theme = "reterminal"
paginate = 5
themesDir = "../.."

enableRobotsTXT = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true
  noindex = false
[params.metaRobots]
  assumeProduction = true
  forceNoindex = false
  disableAutoIndex = false
  indexValue = "follow, index"
  noindexValue = "noindex, nofollow"


[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        weight = 2
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
      [[languages.en.menu.main]]
        weight = 3
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
      [[languages.en.menu.main]]
        weight = 4
        identifier = "cookbook"
        name = "Cookbook"
        url = "/cookbook/"
